### ISSUE TITLE
设置似乎没有被引用,比如设置了所有RecodeFlv为1等 打印出来扔是0

### ISSUE THREAD

**Issue by amhoho** [KouChongYang/rtmpServerStudy#32]
这样设置也失效就没有意义了
比如下文这样的就无效.
```
UserConf:
  PublishDomain:
    127.0.0.1:
      UniqueName: test
      App:
        live:
          GopCacheNum: 2
          ExtTimeSend: 1
          RecodeFlv: 1
          RecodeHls: 1
          hlsFragment: "5s"
          RecodeFlvPath: "/root/go/src"
          RecodeHlsPath: "/root/go/src"
          RecodePicture: 0
```
